CREATE TABLE "planilla" (
	"planilla.numero" int NOT NULL,
	"planilla.fecha" date,
	"participacion_comunitaria.administracion" boolean DEFAULT 'FALSE',
	"participacion_comunitaria.sabe" varchar DEFAULT 'NULL',
	"participacion_comunitaria.constitucion" boolean DEFAULT 'FALSE',
	"participacion_comunitaria.propia" boolean DEFAULT 'FALSE',
	"participacion_comunitaria.misiones" varchar(50),
	"participacion_comunitaria.apoya" boolean DEFAULT 'FALSE',
	"participacion_comunitaria.org_comunitarias" boolean DEFAULT 'FALSE',
	"participacion_comunitaria.area" varchar(50),
	"participacion_comunitaria.familia" boolean DEFAULT 'FALSE',
	"vivienda.terreno_propio" boolean DEFAULT 'FALSE',
	"vivienda.plagas" varchar(50),
	"vivienda.forma_tenencia" varchar(50),
	"vivienda.ocv" boolean DEFAULT 'FALSE',
	"vivienda.techo" varchar(50),
	"vivienda.tipo" varchar(50),
	"vivienda.cond_salubridad" varchar(50),
	"vivienda.enseres" varchar(50),
	"vivienda.mascotas" varchar(50),
	"vivienda.paredes" varchar(50),
	"servicios.recoleccion_basura" varchar(50),
	"servicios.gas" varchar(50),
	"servicios.aguas_servidas" varchar(50),
	"servicios.aguas_blancas" varchar(50),
	"servicios.transporte" varchar(50),
	"servicios.servicios_comunales" varchar(50),
	"servicios.electricidad" varchar(50),
	"servicios.telefonia" varchar(50),
	"servicios.medios" varchar(50) ,
	"salud.ayuda_especial" varchar(50) DEFAULT 'NULL',
	"salud.historia_familiar" varchar(50),
	"situacion_de_exclusion.tercera_edad" int DEFAULT '0',
	"situacion_de_exclusion.enfermedades_terminales" int DEFAULT '0',
	"situacion_de_exclusion.indigentes" int DEFAULT '0',
	"situacion_de_exclusion.niños_de_la_calle" int DEFAULT '0',
	"situacion_de_exclusion.discapacitado" int DEFAULT '0',
	"situacion_laboral.tarjeta" boolean DEFAULT 'TRUE',
	"situacion_labural.cta_banco" boolean DEFAULT 'TRUE',
	"situacion_laboral.ticket" boolean DEFAULT 'FALSE',
	"situacion_laboral.ingreso_familiar" int,
	"situacion_laboral.trabajo" varchar(50),
	"situacion_laboral.comercio_en_casa" varchar(50),
	"comunidad.nombre" varchar(50) NOT NULL,	
	"sector.cp" int NOT NULL,
	PRIMARY KEY ("planilla.numero"),
	FOREIGN KEY ("comunidad.nombre","sector.cp") REFERENCES "comunidad"
); 
