
DROP TABLE IF EXISTS "planilla_parroquia" CASCADE;

DROP TABLE IF EXISTS "encuestador" CASCADE;

DROP TABLE IF EXISTS "grupo_familiar" CASCADE;

DROP TABLE IF EXISTS "planilla" CASCADE;

DROP TABLE IF EXISTS "municipio" CASCADE;

DROP TABLE IF EXISTS "estado" CASCADE;

DROP TABLE IF EXISTS "comunidad" CASCADE;

DROP TABLE IF EXISTS "sector" CASCADE;
