CREATE TABLE "grupo_familiar" (
	"encuestado.no_ci" int NOT NULL ,
	"planilla.numero" int NOT NULL ,
	"encuestado.jefe_ci" int NOT NULL ,
	"encuestado.profesion" varchar(20) ,
	"encuestado.nombre_y_apellido" varchar(40) NOT NULL,
	"encuestado.instruccion" varchar(15) NOT NULL,
	"encuestado.edad" int NOT NULL DEFAULT 0,
	"encuestado.ingreso_mensual" float(10) NOT NULL DEFAULT 0,
	"encuestado.estado_civil" varchar(10) NOT NULL,
	"encuestado.sexo" boolean NOT NULL,
	"jefe.fecha_de_nacimiento" date,
	"jefe.dedicacion_actual" varchar(20),
	"jefe.trabaja_actualmente" boolean,
	"jefe.forma_de_cobro" varchar(30),
	"jefe.telefono.celular" int,
	"jefe.telefono.oficina" int,
	"jefe.telefono.habitacion" int,
	"jefe.email" varchar(50),
	"situacion_comunidad.ventajas" varchar(50),
	"situacion_comunitaria.desventajas" varchar(50),
	PRIMARY KEY ("encuestado.no_ci"),
	FOREIGN KEY ("planilla.numero") REFERENCES "planilla",
	FOREIGN KEY ("encuestado.jefe_ci") REFERENCES "grupo_familiar"("encuestado.no_ci")
);
