CREATE TABLE "grupo_familiar" (
	"encuestado.no_ci" uint NOT NULL ,
	"planilla.numero" uint NOT NULL ,
	"encuestado.jefe_ci" uint NOT NULL ,
	"encuestado.profesion" varchar(20) ,
	"encuestado.nombre_y_apellido" varchar(40) NOT NULL,
	"encuestado.instruccion" instruccion NOT NULL,
	"encuestado.edad" uint NOT NULL DEFAULT 0,
	"encuestado.ingreso_mensual" float(10) NOT NULL DEFAULT 0,
	"encuestado.estado_civil" estado_civil NOT NULL,
	"encuestado.sexo" sexo NOT NULL,
	"encuestado.parentezco" parentezco NOT NULL,
	"jefe.fecha_de_nacimiento" date,
	"jefe.dedicacion_actual" varchar(20),
	"jefe.trabaja_actualmente" boolean,
	"jefe.forma_de_cobro" varchar(30),
	"jefe.telefono.celular" uint,
	"jefe.telefono.oficina" uint,
	"jefe.telefono.habitacion" uint,
	"jefe.email" varchar(50),
	"situacion_comunidad.ventajas" varchar(50),
	"situacion_comunitaria.desventajas" varchar(50),
	PRIMARY KEY ("encuestado.no_ci"),
	FOREIGN KEY ("planilla.numero") REFERENCES "planilla",
	FOREIGN KEY ("encuestado.jefe_ci") REFERENCES "grupo_familiar"("encuestado.no_ci")
);
