INSERT INTO "comunidad" VALUES('Biruaca', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Biruaca', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Biruaca', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Biruaca', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Churuguara', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Churuguara', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Churuguara', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Churuguara', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Clarines', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Clarines', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Clarines', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Clarines', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('El Dorado', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('El Dorado', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('El Dorado', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('El Dorado', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Guanta', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Guanta', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Guanta', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Guanta', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Pariaguán', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Pariaguán', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Pariaguán', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Pariaguán', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('San Antonio de los Altos', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('San Antonio de los Altos', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('San Antonio de los Altos', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('San Antonio de los Altos', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Sanare', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Sanare', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Sanare', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Sanare', NULL , NULL, 4 );
INSERT INTO "comunidad" VALUES('Santa Cruz de Aragua', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Santa Cruz de Aragua', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Santa Cruz de Aragua', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Santa Cruz de Aragua', NULL , NULL );
INSERT INTO "comunidad" VALUES('Táriba', NULL , NULL, 1 );
INSERT INTO "comunidad" VALUES('Táriba', NULL , NULL, 2 );
INSERT INTO "comunidad" VALUES('Táriba', NULL , NULL, 3 );
INSERT INTO "comunidad" VALUES('Táriba', NULL , NULL, 4 );
