INSERT INTO "municipio" VALUES('Andrés Eloy Blanco', 1 ,'Lara');
INSERT INTO "municipio" VALUES('Andrés Eloy Blanco', 2 ,'Lara');
INSERT INTO "municipio" VALUES('Andrés Eloy Blanco', 3 ,'Lara');
INSERT INTO "municipio" VALUES('Andrés Eloy Blanco', 4 ,'Lara');
INSERT INTO "municipio" VALUES('Biruaca', 1 ,'Apure');
INSERT INTO "municipio" VALUES('Biruaca', 2 ,'Apure');
INSERT INTO "municipio" VALUES('Biruaca', 3 ,'Apure');
INSERT INTO "municipio" VALUES('Biruaca', 4 ,'Apure');
INSERT INTO "municipio" VALUES('Bruzual', 1 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Bruzual', 2 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Bruzual', 3 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Bruzual', 4 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Cárdenas', 1 ,'Táchira');
INSERT INTO "municipio" VALUES('Cárdenas', 2 ,'Táchira');
INSERT INTO "municipio" VALUES('Cárdenas', 3 ,'Táchira');
INSERT INTO "municipio" VALUES('Cárdenas', 4 ,'Táchira');
INSERT INTO "municipio" VALUES('Federación', 1 ,'Falcón');
INSERT INTO "municipio" VALUES('Federación', 2 ,'Falcón');
INSERT INTO "municipio" VALUES('Federación', 3 ,'Falcón');
INSERT INTO "municipio" VALUES('Federación', 4 ,'Falcón');
INSERT INTO "municipio" VALUES('Francisco de Miranda', 1 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Francisco de Miranda', 2 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Francisco de Miranda', 3 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Francisco de Miranda', 4 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Guanta', 1 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Guanta', 2 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Guanta', 3 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('Guanta', 4 ,'Anzoátegui');
INSERT INTO "municipio" VALUES('José Angel Lamas', 1 ,'Aragua');
INSERT INTO "municipio" VALUES('José Angel Lamas', 2 ,'Aragua');
INSERT INTO "municipio" VALUES('José Angel Lamas', 3 ,'Aragua');
INSERT INTO "municipio" VALUES('José Angel Lamas', 4 ,'Aragua');
INSERT INTO "municipio" VALUES('Los Salias', 1 ,'Miranda');
INSERT INTO "municipio" VALUES('Los Salias', 2 ,'Miranda');
INSERT INTO "municipio" VALUES('Los Salias', 3 ,'Miranda');
INSERT INTO "municipio" VALUES('Los Salias', 4 ,'Miranda');
INSERT INTO "municipio" VALUES('Sifontes', 1 ,'Bolívar');
INSERT INTO "municipio" VALUES('Sifontes', 2 ,'Bolívar');
INSERT INTO "municipio" VALUES('Sifontes', 3 ,'Bolívar');
INSERT INTO "municipio" VALUES('Sifontes', 4 ,'Bolívar');
